### ISSUE TITLE
Here are some problem when i run the install_env.sh to set up your environment configuration ! ! !

### ISSUE THREAD

**Issue by CozyHUA** [DeepWave-KAUST/Siamese_FWI#1]
When i run "install_env.sh" directly in my terminal, here are some errors I met：

(base) chenrh@amax-4seismic:~/Siamese_FWI-main/Siamese_FWI-main$ sh install_env.sh
Creating Package environment
Channels:
 - nvidia
 - conda-forge
 - pytorch
 - defaults
 - https://mirrors.ustc.edu.cn/anaconda/pkgs/main
 - https://mirrors.ustc.edu.cn/anaconda/pkgs/free
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:
                                                                                                                                 
Preparing transaction: done                                                                                                      
Verifying transaction: done                                                                                                      
Executing transaction: - By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html                                                
                                                                                                                                 
done                                                                                                                             
Installing pip dependencies: - Ran pip subprocess with arguments: 

['/home/chenrh/anaconda3/envs/FWIGAN/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/chenrh/Siamese_FWI-main/Siamese_FWI-main/condaenv.31nbzgie.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting cgds==0.4.5 (from -r /home/chenrh/Siamese_FWI-main/Siamese_FWI-main/condaenv.31nbzgie.requirements.txt (line 1))
  Obtaining dependency information for cgds==0.4.5 from https://files.pythonhosted.org/packages/81/36/d14c27dcf0b87e05f5061bcb868ebeda463b0d0913ea34061420c7e9333a/CGDs-0.4.5-py3-none-any.whl.metadata
  Using cached CGDs-0.4.5-py3-none-any.whl.metadata (3.7 kB)
Collecting cycler==0.12.1 (from -r /home/chenrh/Siamese_FWI-main/Siamese_FWI-main/condaenv.31nbzgie.requirements.txt (line 2))
  Obtaining dependency information for cycler==0.12.1 from https://files.pythonhosted.org/packages/e7/05/c19819d5e3d95294a6f5947fb9b9629efb316b96de511b418c53d245aae6/cycler-0.12.1-py3-none-any.whl.metadata
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting dataclasses==0.6 (from -r /home/chenrh/Siamese_FWI-main/Siamese_FWI-main/condaenv.31nbzgie.requirements.txt (line 3))
  Obtaining dependency information for dataclasses==0.6 from https://files.pythonhosted.org/packages/26/2f/1095cdc2868052dd1e64520f7c0d5c8c550ad297e944e641dbf1ffbb9a5d/dataclasses-0.6-py3-none-any.whl.metadata
  Using cached dataclasses-0.6-py3-none-any.whl.metadata (3.0 kB)
Collecting deepwave==0.0.8 (from -r /home/chenrh/Siamese_FWI-main/Siamese_FWI-main/condaenv.31nbzgie.requirements.txt (line 4))
  Using cached deepwave-0.0.8.tar.gz (32 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: There was an error checking the latest version of pip.

failed

CondaEnvException: Pip failed

install_env.sh: 12: source: not found

CondaError: Run 'conda init' before 'conda activate'

Created and activated environment: /home/chenrh/anaconda3/bin/python
Checking torch version and running a command...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'
Done!

Could you help me to solve this error? Sincere gratitude !!!!

**Comment by omarmohamed15** [comment]
Hey Chen,

There is probably a conflict between the DeepWave, torch, and your Cuda versions.

1- After activating the created environment:
conda activate FWIGAN

2- Choose the right cuda and torch according to your machine and GPU card:
https://pytorch.org/get-started/previous-versions/

3- Install the deepwave 0.0.8 library:
pip install deepwave==0.0.8
