### ISSUE TITLE
Why the result is no satisfactory

### ISSUE THREAD

**Issue by kimkin19212** [DeepWave-KAUST/Siamese_FWI#2]
I run your codes but the result is not like yours.I check the output and cut off it like this:
Epoch: 1 Loss:  10.351574023564657 lr_DL: 0.0001 lr_vel: 80 SNR: 16.362351867455676 SSIM: 0.0062018805
Epoch: 2 Loss:  9.97602564493815 lr_DL: 0.0001 lr_vel: 80 SNR: 16.176525264118006 SSIM: -0.00019684974
Epoch: 3 Loss:  9.166431760787964 lr_DL: 0.0001 lr_vel: 80 SNR: 16.09213404274518 SSIM: 0.029082473
Epoch: 4 Loss:  8.587385829289754 lr_DL: 0.0001 lr_vel: 80 SNR: 16.062649434221335 SSIM: 0.03242259
Epoch: 5 Loss:  7.539551750818888 lr_DL: 0.0001 lr_vel: 80 SNR: 16.082977376714204 SSIM: 0.038330168
Epoch: 6 Loss:  6.797721529006958 lr_DL: 0.0001 lr_vel: 80 SNR: 16.252076498499328 SSIM: 0.061549917
Epoch: 7 Loss:  5.463995186487834 lr_DL: 0.0001 lr_vel: 80 SNR: 16.248109141225363 SSIM: 0.061241474
Epoch: 8 Loss:  3.745332606633504 lr_DL: 0.0001 lr_vel: 80 SNR: 16.349319220718215 SSIM: 0.073665164
Epoch: 9 Loss:  2.550688111782074 lr_DL: 0.0001 lr_vel: 80 SNR: 16.304244681734396 SSIM: 0.07455504
Epoch: 10 Loss:  2.4866937001546225 lr_DL: 0.0001 lr_vel: 80 SNR: 16.276766019957204 SSIM: 0.09139842
Epoch: 11 Loss:  2.3973119537035625 lr_DL: 0.0001 lr_vel: 80 SNR: 16.14571620154893 SSIM: 0.1011951
Epoch: 12 Loss:  2.7401902079582214 lr_DL: 0.0001 lr_vel: 80 SNR: 15.440581174079659 SSIM: 0.09609479
Epoch: 13 Loss:  2.534318129221598 lr_DL: 0.0001 lr_vel: 80 SNR: 15.109351946529387 SSIM: 0.11046278
Epoch: 14 Loss:  2.303466602166494 lr_DL: 0.0001 lr_vel: 80 SNR: 14.854084527349155 SSIM: 0.11865507
Epoch: 15 Loss:  2.1024189551671344 lr_DL: 0.0001 lr_vel: 80 SNR: 14.611113884185038 SSIM: 0.11821876
Epoch: 16 Loss:  1.94879812002182 lr_DL: 0.0001 lr_vel: 80 SNR: 14.304420517086985 SSIM: 0.12161664
Epoch: 17 Loss:  1.8490671316782634 lr_DL: 0.0001 lr_vel: 80 SNR: 13.847896099233981 SSIM: 0.123897135
Epoch: 18 Loss:  1.7357760667800903 lr_DL: 0.0001 lr_vel: 80 SNR: 13.16769319437336 SSIM: 0.12331787
Epoch: 19 Loss:  1.610723320643107 lr_DL: 0.0001 lr_vel: 80 SNR: 12.645095122259422 SSIM: 0.10451798
Epoch: 20 Loss:  2.806677116950353 lr_DL: 0.0001 lr_vel: 80 SNR: 11.855910666447238 SSIM: 0.07753842
Epoch: 21 Loss:  2.2055429657300314 lr_DL: 0.0001 lr_vel: 80 SNR: 11.418961355243102 SSIM: 0.0726473
Epoch: 22 Loss:  1.887986574570338 lr_DL: 0.0001 lr_vel: 80 SNR: 11.164513560566697 SSIM: 0.078952976
Epoch: 23 Loss:  1.599573838710785 lr_DL: 0.0001 lr_vel: 80 SNR: 10.937130411914628 SSIM: 0.087394595
Epoch: 24 Loss:  1.6730708758036295 lr_DL: 0.0001 lr_vel: 80 SNR: 10.853714979044003 SSIM: 0.088399656
Epoch: 25 Loss:  1.4472245156764985 lr_DL: 0.0001 lr_vel: 80 SNR: 10.689279789958196 SSIM: 0.08904825
Epoch: 26 Loss:  1.4068851908047995 lr_DL: 0.0001 lr_vel: 80 SNR: 10.598195897087457 SSIM: 0.089623176
Epoch: 27 Loss:  1.3236143608887991 lr_DL: 0.0001 lr_vel: 80 SNR: 10.534312722285366 SSIM: 0.09182289
Epoch: 28 Loss:  1.4779898325602214 lr_DL: 0.0001 lr_vel: 80 SNR: 10.478816348844083 SSIM: 0.087372504
Epoch: 29 Loss:  1.435812477270762 lr_DL: 0.0001 lr_vel: 80 SNR: 10.406930674727011 SSIM: 0.0873321
Epoch: 30 Loss:  1.361411017179489 lr_DL: 0.0001 lr_vel: 80 SNR: 10.332142438273124 SSIM: 0.08464506
Epoch: 31 Loss:  1.2959014097849528 lr_DL: 0.0001 lr_vel: 80 SNR: 10.223383781875688 SSIM: 0.0847868
Epoch: 32 Loss:  1.4918251276016234 lr_DL: 0.0001 lr_vel: 80 SNR: 10.106558615865875 SSIM: 0.0798438
Epoch: 33 Loss:  1.7067497968673706 lr_DL: 0.0001 lr_vel: 80 SNR: 10.019969652252298 SSIM: 0.0801704
Epoch: 34 Loss:  1.6188759287198384 lr_DL: 0.0001 lr_vel: 80 SNR: 9.831877927732112 SSIM: 0.07541272
Epoch: 35 Loss:  1.7366687218348185 lr_DL: 0.0001 lr_vel: 80 SNR: 9.69056310483701 SSIM: 0.07354195
Epoch: 36 Loss:  1.3040010154247283 lr_DL: 0.0001 lr_vel: 80 SNR: 9.619332457521626 SSIM: 0.072854124
Epoch: 37 Loss:  1.233640374739965 lr_DL: 0.0001 lr_vel: 80 SNR: 9.534093261990717 SSIM: 0.07162725
Epoch: 38 Loss:  1.2447665671507517 lr_DL: 0.0001 lr_vel: 80 SNR: 9.371842711393603 SSIM: 0.071097754
Epoch: 39 Loss:  1.3324949463208517 lr_DL: 0.0001 lr_vel: 80 SNR: 9.339405550451264 SSIM: 0.07170044
Epoch: 40 Loss:  1.9471197326978047 lr_DL: 0.0001 lr_vel: 80 SNR: 9.319422409267347 SSIM: 0.072411306
Epoch: 41 Loss:  1.22246955037117 lr_DL: 0.0001 lr_vel: 80 SNR: 9.284764121785628 SSIM: 0.07140431
Epoch: 42 Loss:  1.2070470988750457 lr_DL: 0.0001 lr_vel: 80 SNR: 9.229105104758368 SSIM: 0.07179863
Epoch: 43 Loss:  1.201651825507482 lr_DL: 0.0001 lr_vel: 80 SNR: 9.178556881403072 SSIM: 0.06986182
Epoch: 44 Loss:  1.127402764558792 lr_DL: 0.0001 lr_vel: 80 SNR: 9.123743451910439 SSIM: 0.06988234
Epoch: 45 Loss:  1.2074920177459716 lr_DL: 0.0001 lr_vel: 80 SNR: 9.072393189066174 SSIM: 0.069318846
Epoch: 46 Loss:  1.0710679809252421 lr_DL: 0.0001 lr_vel: 80 SNR: 8.977052484154514 SSIM: 0.06842244
Epoch: 47 Loss:  1.2093161741892497 lr_DL: 0.0001 lr_vel: 80 SNR: 8.914761940167947 SSIM: 0.06724808
Epoch: 48 Loss:  1.387329250574112 lr_DL: 0.0001 lr_vel: 80 SNR: 8.856177475356708 SSIM: 0.06620721
Epoch: 49 Loss:  1.1506304800510407 lr_DL: 0.0001 lr_vel: 80 SNR: 8.794617790735618 SSIM: 0.066895515
Epoch: 50 Loss:  1.0895620703697204 lr_DL: 0.0001 lr_vel: 80 SNR: 8.751321345508517 SSIM: 0.06764713
Epoch: 51 Loss:  1.2365181525548299 lr_DL: 0.0001 lr_vel: 80 SNR: 8.74080349805764 SSIM: 0.06772073
Epoch: 52 Loss:  1.0839036802450817 lr_DL: 0.0001 lr_vel: 80 SNR: 8.69108886584007 SSIM: 0.06415146
Epoch: 53 Loss:  1.0167207996050516 lr_DL: 0.0001 lr_vel: 80 SNR: 8.675098724858243 SSIM: 0.06332434
Epoch: 54 Loss:  1.1206719736258188 lr_DL: 0.0001 lr_vel: 80 SNR: 8.60960342514876 SSIM: 0.063500516
Epoch: 55 Loss:  1.4149728576342264 lr_DL: 0.0001 lr_vel: 80 SNR: 8.569265421278644 SSIM: 0.06301167
Epoch: 56 Loss:  4.23783900141716 lr_DL: 0.0001 lr_vel: 80 SNR: 8.547014891579948 SSIM: 0.06271832
Epoch: 57 Loss:  3.8538988252480824 lr_DL: 0.0001 lr_vel: 80 SNR: 8.489558934952335 SSIM: 0.06585128
Epoch: 58 Loss:  1.7714070081710815 lr_DL: 0.0001 lr_vel: 80 SNR: 8.422710336318676 SSIM: 0.0665139
Epoch: 59 Loss:  1.7767572363217672 lr_DL: 0.0001 lr_vel: 80 SNR: 8.391759449073984 SSIM: 0.06323375
Epoch: 60 Loss:  1.5950121025244395 lr_DL: 0.0001 lr_vel: 80 SNR: 8.333544814432432 SSIM: 0.06456465
Epoch: 61 Loss:  1.2825566629568736 lr_DL: 0.0001 lr_vel: 80 SNR: 8.283082276037096 SSIM: 0.06442422
Epoch: 62 Loss:  1.301849933465322 lr_DL: 0.0001 lr_vel: 80 SNR: 8.219669974798759 SSIM: 0.06415752
Epoch: 63 Loss:  2.5425524433453877 lr_DL: 0.0001 lr_vel: 80 SNR: 8.169179735534577 SSIM: 0.06331544
Epoch: 64 Loss:  1.4611265242099762 lr_DL: 0.0001 lr_vel: 80 SNR: 8.092735709829027 SSIM: 0.06446633
Epoch: 65 Loss:  1.293279868364334 lr_DL: 0.0001 lr_vel: 80 SNR: 8.056247022729515 SSIM: 0.06468949
Epoch: 66 Loss:  1.0197114507357279 lr_DL: 0.0001 lr_vel: 80 SNR: 7.95511350736418 SSIM: 0.065126196
Epoch: 67 Loss:  1.0402792910734813 lr_DL: 0.0001 lr_vel: 80 SNR: 7.911873257522995 SSIM: 0.06500397
Epoch: 68 Loss:  2.458499902486801 lr_DL: 0.0001 lr_vel: 80 SNR: 7.8756719397264785 SSIM: 0.06673385
Epoch: 69 Loss:  7.104906407992045 lr_DL: 0.0001 lr_vel: 80 SNR: 7.838448387726239 SSIM: 0.06623903
Epoch: 70 Loss:  4.071317672729492 lr_DL: 0.0001 lr_vel: 80 SNR: 7.792767365963851 SSIM: 0.06591936
Epoch: 71 Loss:  1.028012712796529 lr_DL: 0.0001 lr_vel: 80 SNR: 7.761259947035841 SSIM: 0.06672148
Epoch: 72 Loss:  1.0276018838087717 lr_DL: 0.0001 lr_vel: 80 SNR: 7.768877903272538 SSIM: 0.06681321
Epoch: 73 Loss:  1.0021961291631063 lr_DL: 0.0001 lr_vel: 80 SNR: 7.738318555278292 SSIM: 0.067545764
Epoch: 74 Loss:  1.0180660088857014 lr_DL: 0.0001 lr_vel: 80 SNR: 7.687803208483212 SSIM: 0.06785425
Epoch: 75 Loss:  0.9860810299714406 lr_DL: 0.0001 lr_vel: 80 SNR: 7.662769626485 SSIM: 0.06851973
Epoch: 76 Loss:  1.0607322176297507 lr_DL: 0.0001 lr_vel: 80 SNR: 7.636295718749655 SSIM: 0.06896818
Epoch: 77 Loss:  2.9444640497366588 lr_DL: 0.0001 lr_vel: 80 SNR: 7.599801790587643 SSIM: 0.06956841
Epoch: 78 Loss:  1.0544667661190033 lr_DL: 0.0001 lr_vel: 80 SNR: 7.571308612214953 SSIM: 0.0695649
Epoch: 79 Loss:  1.004277894894282 lr_DL: 0.0001 lr_vel: 80 SNR: 7.517422453359241 SSIM: 0.069361575
Epoch: 80 Loss:  1.0223301847775776 lr_DL: 0.0001 lr_vel: 80 SNR: 7.492575013978269 SSIM: 0.06932511
Epoch: 81 Loss:  1.0529242515563966 lr_DL: 0.0001 lr_vel: 80 SNR: 7.49602875301017 SSIM: 0.06933307
Epoch: 82 Loss:  0.9896667242050171 lr_DL: 0.0001 lr_vel: 80 SNR: 7.4783390287959985 SSIM: 0.06951955
Epoch: 83 Loss:  1.0251952409744263 lr_DL: 0.0001 lr_vel: 80 SNR: 7.418260233306151 SSIM: 0.069503695
Epoch: 84 Loss:  1.0742672681808472 lr_DL: 0.0001 lr_vel: 80 SNR: 7.381201658925265 SSIM: 0.069415435
Epoch: 85 Loss:  1.1206549763679505 lr_DL: 0.0001 lr_vel: 80 SNR: 7.369771607529286 SSIM: 0.069264114
Epoch: 86 Loss:  2.1463806509971617 lr_DL: 0.0001 lr_vel: 80 SNR: 7.339352051342205 SSIM: 0.06917602
Epoch: 87 Loss:  1.5537341058254241 lr_DL: 0.0001 lr_vel: 80 SNR: 7.337576764490241 SSIM: 0.07015114
Epoch: 88 Loss:  1.4044778724511464 lr_DL: 0.0001 lr_vel: 80 SNR: 7.310430846556319 SSIM: 0.07004595
Epoch: 89 Loss:  0.9662552177906036 lr_DL: 0.0001 lr_vel: 80 SNR: 7.268587798836234 SSIM: 0.068804756
Epoch: 90 Loss:  0.9444088637828827 lr_DL: 0.0001 lr_vel: 80 SNR: 7.25355892641219 SSIM: 0.068496965
Epoch: 91 Loss:  1.5963368674119314 lr_DL: 0.0001 lr_vel: 80 SNR: 7.230647392498161 SSIM: 0.06838236
Epoch: 92 Loss:  1.0034093896547953 lr_DL: 0.0001 lr_vel: 80 SNR: 7.210346187899367 SSIM: 0.06833805
Epoch: 93 Loss:  1.1747933526833851 lr_DL: 0.0001 lr_vel: 80 SNR: 7.217286638371378 SSIM: 0.06828445
Epoch: 94 Loss:  1.0447076479593913 lr_DL: 0.0001 lr_vel: 80 SNR: 7.186098903530068 SSIM: 0.06819741
Epoch: 95 Loss:  0.9296274423599243 lr_DL: 0.0001 lr_vel: 80 SNR: 7.152577743925513 SSIM: 0.06816432
Epoch: 96 Loss:  0.91768679022789 lr_DL: 0.0001 lr_vel: 80 SNR: 7.128505142366021 SSIM: 0.06814349
Epoch: 97 Loss:  0.915176119407018 lr_DL: 0.0001 lr_vel: 80 SNR: 7.105782869319515 SSIM: 0.06808553
Epoch: 98 Loss:  0.9128816554943721 lr_DL: 0.0001 lr_vel: 80 SNR: 7.077000519719014 SSIM: 0.06807009
Epoch: 99 Loss:  1.2050488571325937 lr_DL: 0.0001 lr_vel: 80 SNR: 7.052593989799209 SSIM: 0.068062894
Epoch: 100 Loss:  0.8830060452222824 lr_DL: 0.0001 lr_vel: 80 SNR: 7.031346476503925 SSIM: 0.06795514

the subsequent epoch is similiar like this,and I get the result in here:
![Snipaste_2024-12-23_13-51-20](https://github.com/user-attachments/assets/84e2cc2b-ad95-453a-bee7-d219493ba90a)

**Comment by omarmohamed15** [comment]
Hey @kimkin19212 

Thank you for your inquiry. Some versions of PyTorch may exhibit instability with the optimizer, which can prevent convergence. Please try using the same version we used: `pytorch==1.10.1=py3.9_cuda11.3_cudnn8.2.0_0`. Alternatively, you can experiment with a different version of PyTorch. Let me know if you encounter the same issue.
